options:
  nginx:
    port:
      type: int
      default: 80
      description: |
        NGINX listen port
    host:
      type: string
      default: '127.0.0.1'
      description: |
        NGINX listen address 
  gunicorn:        
    workers:
      default: 2
      type: int
      description: |
        Amount of gunicorn workers
